# Generated by Django 3.2.16 on 2022-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
